<a href="https://colab.research.google.com/github/KirtiNayak11/FlightPricePrediction/blob/main/Flight_Price_Prediction_VarianceThreshold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Clean_Dataset[1].csv')
df.head()

Unnamed: 0   airline   flight source_city departure_time stops  \
0           0  SpiceJet  SG-8709       Delhi        Evening  zero   
1           1  SpiceJet  SG-8157       Delhi  Early_Morning  zero   
2           2   AirAsia   I5-764       Delhi  Early_Morning  zero   
3           3   Vistara   UK-995       Delhi        Morning  zero   
4           4   Vistara   UK-963       Delhi        Morning  zero   

    arrival_time destination_city    class  duration  days_left  price  
0          Night           Mumbai  Economy      2.17          1   5953  
1        Morning           Mumbai  Economy      2.33          1   5953  
2  Early_Morning           Mumbai  Economy      2.17          1   5956  
3      Afternoon           Mumbai  Economy      2.25          1   5955  
4        Morning           Mumbai  Economy      2.33          1   5955

In [ ]:
df.sample(10)

Unnamed: 0    airline   flight source_city departure_time  \
16860        16860  Air_India   AI-885       Delhi        Morning   
148703      148703    Vistara   UK-706     Kolkata        Morning   
123702      123702    Vistara   UK-772     Kolkata        Morning   
140381      140381  Air_India   AI-763     Kolkata  Early_Morning   
107422      107422   GO_FIRST   G8-395   Bangalore        Morning   
239175      239175    Vistara   UK-994      Mumbai        Morning   
10808        10808     Indigo  6E-2331       Delhi  Early_Morning   
62979        62979  Air_India   AI-651      Mumbai        Morning   
168641      168641    Vistara   UK-890   Hyderabad        Evening   
12165        12165    AirAsia   I5-792       Delhi      Afternoon   

              stops arrival_time destination_city     class  duration  \
16860           one        Night        Bangalore   Economy     11.58   
148703  two_or_more      Morning          Chennai   Economy     22.58   
123702          one   Late_Night            Delhi   Economy     14.50   
140381          one   Late_Night        Bangalore   Economy     17.17   
107422          one        Night          Kolkata   Economy     15.42   
239175          one      Evening        Hyderabad  Business      9.50   
10808           one    Afternoon        Bangalore   Economy      6.58   
62979           one      Morning          Kolkata   Economy     23.17   
168641          one      Morning        Bangalore   Economy     17.17   
12165   two_or_more   Late_Night        Bangalore   Economy     12.00   

        days_left  price  
16860          34  10418  
148703          9  24443  
123702         27   6461  
140381         35   7474  
107422         34   6186  
239175         18  58125  
10808           6   9735  
62979          10  13529  
168641         31   6776  
12165          13   8056

#drop unwanted columns

In [ ]:
df=df.drop(columns=['Unnamed: 0','flight'])

In [ ]:
df.sample(5)

airline source_city departure_time stops arrival_time  \
238431    Vistara      Mumbai      Afternoon   one        Night   
126053  Air_India     Kolkata  Early_Morning   one        Night   
223111  Air_India       Delhi  Early_Morning   one      Morning   
141806    AirAsia     Kolkata        Evening   one    Afternoon   
85311     Vistara   Bangalore        Evening   one      Evening   

       destination_city     class  duration  days_left  price  
238431        Hyderabad  Business      7.17          8  58125  
126053            Delhi   Economy     16.17         41   4347  
223111          Chennai  Business     27.92         21  45257  
141806        Bangalore   Economy     16.67         45   3862  
85311             Delhi   Economy     20.58          8  14988

# Get X and Y attribute

In [ ]:
x=df.drop(['price'],axis=1)
x.head()

airline source_city departure_time stops   arrival_time destination_city  \
0  SpiceJet       Delhi        Evening  zero          Night           Mumbai   
1  SpiceJet       Delhi  Early_Morning  zero        Morning           Mumbai   
2   AirAsia       Delhi  Early_Morning  zero  Early_Morning           Mumbai   
3   Vistara       Delhi        Morning  zero      Afternoon           Mumbai   
4   Vistara       Delhi        Morning  zero        Morning           Mumbai   

     class  duration  days_left  
0  Economy      2.17          1  
1  Economy      2.33          1  
2  Economy      2.17          1  
3  Economy      2.25          1  
4  Economy      2.33          1

In [ ]:
y=df['price']
y.head()

0    5953
1    5953
2    5956
3    5955
4    5955
Name: price, dtype: int64

#train and test split

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=25)

#Checking for null values in the dataset

In [ ]:
df.isna().sum()

airline             0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

#Encoding categorical values to numeric

In [ ]:
df['class'].unique()

array(['Economy', 'Business'], dtype=object)

In [ ]:
df['stops'].unique()

array(['zero', 'one', 'two_or_more'], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse=False,drop='first')
ohe.fit(xtrain[['airline','source_city','departure_time','arrival_time','destination_city']])
xtrainOhe=ohe.transform(xtrain[['airline','source_city','departure_time','arrival_time','destination_city']])
xtrainOhe

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [ ]:
xtestOhe=ohe.transform(xtest[['airline','source_city','departure_time','arrival_time','destination_city']])
xtestOhe

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
ord=OrdinalEncoder(categories=[['zero','one','two_or_more'],['Economy','Business']])
ord.fit(xtrain[['stops','class']])
xtrainOrd=ord.transform(xtrain[['stops','class']])
xtrainOrd

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [0., 0.],
       [2., 0.],
       [0., 0.]])

In [ ]:
xtestOrd=ord.transform(xtest[['stops','class']])
xtestOrd

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 1.],
       [2., 0.],
       [1., 1.]])

#deleting the old columns

In [ ]:
xtrain.sample(5)

airline source_city departure_time stops arrival_time  \
40947     Indigo       Delhi        Morning   one    Afternoon   
185374   AirAsia     Chennai          Night   one   Late_Night   
184488  GO_FIRST     Chennai      Afternoon   one   Late_Night   
6837    GO_FIRST       Delhi      Afternoon  zero      Evening   
112918    Indigo   Bangalore        Morning   one      Evening   

       destination_city    class  duration  days_left  
40947           Chennai  Economy      7.58         37  
185374            Delhi  Economy      5.33         36  
184488            Delhi  Economy     12.25         30  
6837             Mumbai  Economy      2.25         35  
112918        Hyderabad  Economy      7.92         29

In [ ]:
new_xtrain=xtrain.drop(['stops','class','airline','source_city','departure_time','arrival_time','destination_city'],axis=1)

In [ ]:
new_xtrain

duration  days_left
154862      5.25         22
253148      8.33          7
270966     18.33         17
143014      2.17          7
54524      13.58         12
...          ...        ...
130365      6.67         20
92303       2.75         41
6618        2.17         34
90430       8.75         33
29828       2.08         11

[240122 rows x 2 columns]

In [ ]:
new_xtest=xtest.drop(['stops','class','airline','source_city','departure_time','arrival_time','destination_city'],axis=1)

In [ ]:
new_df_xtrain=np.concatenate((new_xtrain,xtrainOrd,xtrainOhe),axis=1)
new_df_xtrain

array([[ 5.25, 22.  ,  1.  , ...,  0.  ,  0.  ,  0.  ],
       [ 8.33,  7.  ,  1.  , ...,  0.  ,  1.  ,  0.  ],
       [18.33, 17.  ,  1.  , ...,  1.  ,  0.  ,  0.  ],
       ...,
       [ 2.17, 34.  ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [ 8.75, 33.  ,  2.  , ...,  0.  ,  0.  ,  0.  ],
       [ 2.08, 11.  ,  0.  , ...,  1.  ,  0.  ,  0.  ]])

In [ ]:
new_df_xtrain.shape

(240122, 29)

In [ ]:
new_df_xtest=np.concatenate((new_xtest,xtestOrd,xtestOhe),axis=1)
new_df_xtest

array([[ 2.17, 11.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [24.58, 13.  ,  1.  , ...,  0.  ,  0.  ,  0.  ],
       [ 8.75, 29.  ,  1.  , ...,  1.  ,  0.  ,  0.  ],
       ...,
       [25.92, 29.  ,  1.  , ...,  0.  ,  1.  ,  0.  ],
       [23.83, 37.  ,  2.  , ...,  0.  ,  0.  ,  1.  ],
       [22.33, 16.  ,  1.  , ...,  0.  ,  1.  ,  0.  ]])

#Applying standard scaler Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
scaler.fit(new_df_xtrain)

MinMaxScaler()

In [ ]:
xtrain_normalized_data = scaler.transform(new_df_xtrain)

In [ ]:
xtest_normalized_data = scaler.transform(new_df_xtest)

In [ ]:
xtrain_normalized_data

array([[0.09020408, 0.4375    , 0.5       , ..., 0.        , 0.        ,
        0.        ],
       [0.15306122, 0.125     , 0.5       , ..., 0.        , 1.        ,
        0.        ],
       [0.35714286, 0.33333333, 0.5       , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.02734694, 0.6875    , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.16163265, 0.66666667, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0255102 , 0.20833333, 0.        , ..., 1.        , 0.        ,
        0.        ]])

#Applying Feature Selection Method

**VarianceThreshold**

In [ ]:
from sklearn.feature_selection import VarianceThreshold

In [ ]:
v=VarianceThreshold(0.15)

In [ ]:
v.fit(xtrain_normalized_data)

VarianceThreshold(threshold=0.15)

In [ ]:
xtrain_v=v.transform(new_df_xtrain)

In [ ]:
print(xtrain_v.shape)  #have no affect

(240122, 13)


In [ ]:
xtrain_v

array([[0., 0., 1., ..., 1., 1., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
xtest_v=v.transform(new_df_xtest)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
linear_model = LinearRegression()

In [ ]:
linear_model.fit(xtrain_v, ytrain)

LinearRegression()

In [ ]:
predictionsl = linear_model.predict(xtest_v)

In [ ]:
predictionsl

array([ 2539.71313173,  7955.48420167,  4458.76234961, ...,
       55567.43347153,  6711.44558538, 55008.84765762])

In [ ]:
predl=predictionsl.astype(int)
predl

array([ 2539,  7955,  4458, ..., 55567,  6711, 55008])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(ytest, predl)

In [ ]:
accuracy

1.665806000233213e-05

In [ ]:
from sklearn.tree import DecisionTreeRegressor

# Create a decision tree regression model
tree_modelDT = DecisionTreeRegressor()

# Fit the model to the training data
tree_modelDT.fit(xtrain_v, ytrain)

# Make predictions on the test data
predictionsDT = tree_modelDT.predict(xtest_v)

In [ ]:
predictionsDT=predictionsDT.astype(int)

In [ ]:
accuracyDT = accuracy_score(ytest, predictionsDT)
accuracyDT

6.663224000932851e-05

In [ ]:
from sklearn.tree import DecisionTreeRegressor

# Create a decision tree regression model
tree_modelRT = DecisionTreeRegressor()

# Fit the model to the training data
tree_modelRT.fit(xtrain_v, ytrain)

# Make predictions on the test data
predictionsRT = tree_modelDT.predict(xtest_v)
predictionsRT=predictionsDT.astype(int)
accuracyRT = accuracy_score(ytest, predictionsRT)
accuracyRT

6.663224000932851e-05

In [ ]:
from sklearn.svm import SVC

# Create a decision tree regression model
svm_model = SVC(kernel='rbf')

# Fit the model to the training data
svm_model.fit(xtrain_v, ytrain)

# Make predictions on the test data
predictionsSVM = svm_model.predict(xtest_v)
predictionsSVM=predictionsSVM.astype(int)
accuracySVM = accuracy_score(ytest, predictionsRT)
accuracySVM